stages:
  - build
  - test

# Cache
cache: &dependency_cache
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - subprojects/girara
    - subprojects/zathura

# Archlinux
build:archlinux:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/archlinux:latest
  script:
    - mkdir -p build && cd build
    - meson ..
    - ninja
  cache:
    <<: *dependency_cache
  artifacts:
    expire_in: 1 day
    paths:
      - build
  except:
    - tags

# Debian 12 (bookworm)
build:debian-bookworm:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:bookworm
  script:
    - mkdir -p build && cd build
    - meson ..
    - ninja
  cache:
    <<: *dependency_cache
  artifacts:
    expire_in: 1 day
    paths:
      - build
  except:
    - tags

# Debian 13 (trixie)
build:debian-trixie:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:trixie
  script:
    - mkdir -p build && cd build
    - meson ..
    - ninja
  cache:
    <<: *dependency_cache
  artifacts:
    expire_in: 1 day
    paths:
      - build
  except:
    - tags

# Ubuntu 22.04 LTS (jammy)
build:ubuntu-jammy:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/ubuntu:jammy
  script:
    - mkdir -p build && cd build
    - meson ..
    - ninja
  cache:
    <<: *dependency_cache
  artifacts:
    expire_in: 1 day
    paths:
      - build
  except:
    - tags
